### PR TITLE
changes related to latest azure-iot-sk

### PR DESCRIPTION
**Pull request by shjala**
Minor changes to make this compile and work with the latest azure-iot-sdk-c.

### CODE REVIEW

**Comment by shjala** [comment]
@cshari-zededa @eriknordmark

**Review by cshari-zededa — APPROVED** [review]

**Review by eriknordmark — CHANGES_REQUESTED** [review]
You need to sign to pass the dco check

**Comment by shjala** [comment]
@eriknordmark I have signed all commits, but I my repo has default  "Your Name <you@example.com>" config, that's why it complains. fixed it.

**Review by eriknordmark — APPROVED** [review]
Thanks!

**Pull request merged**
