### PR TITLE
add unit test for vtpm

### PR DESCRIPTION
**Pull request by shjala**
add unit test based on the ut in the azure-iot-sdk, this covers the major operations offered by tpm in azure-iot-edge-runtime.

### CODE REVIEW

**Comment by shjala** [comment]
@eriknordmark @cshari-zededa please review.

**Comment by shjala** [comment]
@cshari-zededa do you have any working code for the `insert_key_in_tpm`? because the one from MS is failing on the `DPS_UNMARSHAL` calls and I'm not sure what is the issue. is there any specific compile flags for struct packing that I should use?

**Comment by cshari-zededa** [comment]
> @cshari-zededa do you have any working code for the `insert_key_in_tpm`? because the one from MS is failing on the `DPS_UNMARSHAL` calls and I'm not sure what is the issue. is there any specific compile flags for struct packing that I should use?

What is the error? You can compare it with our old code and see if there is anything is different:
https://github.com/lf-edge/eve-tools/blob/v2.0.0/azure-on-eve/src/hsm_client_tpm_device.c

**Comment by shjala** [comment]
@cshari-zededa it is our code, I'm linking azure-iot-sdk tests with our code, but test fails. The problem is the `key` in `insert_key_in_tpm(..., const unsigned char* key, size_t key_len)` is not binary blob, but has to be a specific structure because the `DPS_UNMARSHAL` extracts len from the content of it, and I belive the input in the MS test is also wrong. 

I was wondering if we have a working example with a working input for `insert_key_in_tpm` so I can spare myself reading the TPM spec.

**Comment by cshari-zededa** [comment]
> 

My bad, I could not find it saved anywhere.

**Comment by cshari-zededa** [comment]
> > 
> 
> My bad, I could not find it saved anywhere.

Pls see if this can help you to construct the key :


209 | {
-- | --
210 | TpmBuffer actBlob = new TpmBuffer(Arrays.copyOfRange(key, 0, key.length));
211 |  
212 | TPM2B_ID_OBJECT         credBlob = TPM2B_ID_OBJECT.fromTpm(actBlob);
213 | TPM2B_ENCRYPTED_SECRET  encSecret = TPM2B_ENCRYPTED_SECRET.fromTpm(actBlob);
214 | TPM2B_PRIVATE           idKeyDupBlob = TPM2B_PRIVATE.fromTpm(actBlob);
215 | TPM2B_ENCRYPTED_SECRET  encWrapKey = TPM2B_ENCRYPTED_SECRET.fromTpm(actBlob);

taken from 
https://github.com/Azure/azure-iot-sdk-java/blob/214a54007ede4e23002dc17a3cead02784cd0bf8/provisioning/security/tpm-provider/src/main/java/com/microsoft/azure/sdk/iot/provisioning/security/hsm/SecurityProviderTPMHsm.java#L212

**Comment by shjala** [comment]
figured out how to prep the input, and test now passes, do some clean up and will commit soon.

**Comment by shjala** [comment]
@cshari-zededa , @eriknordmark  all tests passing, please review. 
```
root@dev:# make test
{ running} hsm_client_tpm_import_key_succeed
<6>2023-05-22T10:48:28Z [INFO] (../src/hsm_client_tpm_device.c:initialize_tpm_device:414) Reading endorsement key using TPM Service...
<6>2023-05-22T10:48:28Z [INFO] (../src/hsm_client_tpm_device.c:initialize_tpm_device:417) Reading storage key(pub) using TPM service...
<6>2023-05-22T10:48:28Z [INFO] (../src/hsm_client_tpm_device.c:insert_key_in_tpm:365) Activating the provided symmetric key using TPM Service...
<3>2023-05-22T10:48:28Z [ERR!] (../src/hsm_client_tpm_device.c:insert_key_in_tpm:402) Failed to backup DPS privisioning key (part 1)
<3>2023-05-22T10:48:28Z [ERR!] (../src/hsm_client_tpm_device.c:insert_key_in_tpm:405) Failed to backup DPS privisioning key (part 2)
{      ok} hsm_client_tpm_import_key_succeed
{ running} hsm_client_tpm_create_succeed
<6>2023-05-22T10:48:28Z [INFO] (../src/hsm_client_tpm_device.c:initialize_tpm_device:414) Reading endorsement key using TPM Service...
<6>2023-05-22T10:48:28Z [INFO] (../src/hsm_client_tpm_device.c:initialize_tpm_device:417) Reading storage key(pub) using TPM service...
{      ok} hsm_client_tpm_create_succeed
{ running} hsm_client_tpm_import_key_handle_NULL_fail
{      ok} hsm_client_tpm_import_key_handle_NULL_fail
{ running} hsm_client_tpm_import_key_key_NULL_fail
<6>2023-05-22T10:48:28Z [INFO] (../src/hsm_client_tpm_device.c:initialize_tpm_device:414) Reading endorsement key using TPM Service...
<6>2023-05-22T10:48:28Z [INFO] (../src/hsm_client_tpm_device.c:initialize_tpm_device:417) Reading storage key(pub) using TPM service...
{      ok} hsm_client_tpm_import_key_key_NULL_fail
{ running} hsm_client_tpm_get_endorsement_key_handle_NULL_succeed
<3>2023-05-22T10:48:28Z [ERR!] (../src/hsm_client_tpm_device.c:hsm_client_tpm_get_endorsement_key:516) Invalid handle value specified: handle: (nil), result: 0xffffd7966128, result_len: 0xffffd7966130
{      ok} hsm_client_tpm_get_endorsement_key_handle_NULL_succeed
{ running} hsm_client_tpm_get_endorsement_key_size_0_fail
<6>2023-05-22T10:48:28Z [INFO] (../src/hsm_client_tpm_device.c:initialize_tpm_device:414) Reading endorsement key using TPM Service...
<6>2023-05-22T10:48:28Z [INFO] (../src/hsm_client_tpm_device.c:initialize_tpm_device:417) Reading storage key(pub) using TPM service...
<3>2023-05-22T10:48:28Z [ERR!] (../src/hsm_client_tpm_device.c:hsm_client_tpm_get_endorsement_key:516) Invalid handle value specified: handle: (nil), result: 0xffffd7966120, result_len: 0xffffd7966128
{      ok} hsm_client_tpm_get_endorsement_key_size_0_fail
{ running} hsm_client_tpm_get_endorsement_key_succeed
<6>2023-05-22T10:48:28Z [INFO] (../src/hsm_client_tpm_device.c:initialize_tpm_device:414) Reading endorsement key using TPM Service...
<6>2023-05-22T10:48:28Z [INFO] (../src/hsm_client_tpm_device.c:initialize_tpm_device:417) Reading storage key(pub) using TPM service...
<6>2023-05-22T10:48:28Z [INFO] (../src/hsm_client_tpm_device.c:hsm_client_tpm_get_endorsement_key:521) Retrieving endorsement key using TPM service...
{      ok} hsm_client_tpm_get_endorsement_key_succeed
{ running} hsm_client_tpm_get_storage_key_handle_NULL_fail
<3>2023-05-22T10:48:28Z [ERR!] (../src/hsm_client_tpm_device.c:hsm_client_tpm_get_storage_key:543) Invalid handle value specified: handle: (nil), result: 0xffffd7966128, result_len: 0xffffd7966130
{      ok} hsm_client_tpm_get_storage_key_handle_NULL_fail
{ running} hsm_client_tpm_get_storage_key_size_0_fail
<6>2023-05-22T10:48:28Z [INFO] (../src/hsm_client_tpm_device.c:initialize_tpm_device:414) Reading endorsement key using TPM Service...
<6>2023-05-22T10:48:28Z [INFO] (../src/hsm_client_tpm_device.c:initialize_tpm_device:417) Reading storage key(pub) using TPM service...
<3>2023-05-22T10:48:28Z [ERR!] (../src/hsm_client_tpm_device.c:hsm_client_tpm_get_storage_key:543) Invalid handle value specified: handle: (nil), result: 0xffffd7966120, result_len: 0xffffd7966128
{      ok} hsm_client_tpm_get_storage_key_size_0_fail
{ running} hsm_client_tpm_get_storage_key_succeed
<6>2023-05-22T10:48:28Z [INFO] (../src/hsm_client_tpm_device.c:initialize_tpm_device:414) Reading endorsement key using TPM Service...
<6>2023-05-22T10:48:28Z [INFO] (../src/hsm_client_tpm_device.c:initialize_tpm_device:417) Reading storage key(pub) using TPM service...
<6>2023-05-22T10:48:28Z [INFO] (../src/hsm_client_tpm_device.c:hsm_client_tpm_get_storage_key:548) Retrieving Storage key using TPM service...
{      ok} hsm_client_tpm_get_storage_key_succeed
{ running} hsm_client_tpm_sign_data_handle_fail
<3>2023-05-22T10:48:28Z [ERR!] (../src/hsm_client_tpm_device.c:hsm_client_tpm_sign_data:574) Invalid handle value specified handle: (nil), data: 0xaaaad3b0d060, data_size: 128, digest: 0xffffd7966128, digest_size: 0xffffd7966130
{      ok} hsm_client_tpm_sign_data_handle_fail
{ running} hsm_client_tpm_sign_data_data_NULL_fail
<6>2023-05-22T10:48:28Z [INFO] (../src/hsm_client_tpm_device.c:initialize_tpm_device:414) Reading endorsement key using TPM Service...
<6>2023-05-22T10:48:28Z [INFO] (../src/hsm_client_tpm_device.c:initialize_tpm_device:417) Reading storage key(pub) using TPM service...
<3>2023-05-22T10:48:28Z [ERR!] (../src/hsm_client_tpm_device.c:hsm_client_tpm_sign_data:574) Invalid handle value specified handle: 0xaaaad7021160, data: (nil), data_size: 128, digest: 0xffffd7966120, digest_size: 0xffffd7966128
{      ok} hsm_client_tpm_sign_data_data_NULL_fail
{ running} hsm_client_tpm_sign_data_size_0_fail
<6>2023-05-22T10:48:28Z [INFO] (../src/hsm_client_tpm_device.c:initialize_tpm_device:414) Reading endorsement key using TPM Service...
<6>2023-05-22T10:48:28Z [INFO] (../src/hsm_client_tpm_device.c:initialize_tpm_device:417) Reading storage key(pub) using TPM service...
<3>2023-05-22T10:48:28Z [ERR!] (../src/hsm_client_tpm_device.c:hsm_client_tpm_sign_data:574) Invalid handle value specified handle: 0xaaaad7021160, data: 0xaaaad3b0d060, data_size: 0, digest: 0xffffd7966120, digest_size: 0xffffd7966128
{      ok} hsm_client_tpm_sign_data_size_0_fail
{ running} hsm_client_tpm_sign_data_key_NULL_fail
<6>2023-05-22T10:48:28Z [INFO] (../src/hsm_client_tpm_device.c:initialize_tpm_device:414) Reading endorsement key using TPM Service...
<6>2023-05-22T10:48:28Z [INFO] (../src/hsm_client_tpm_device.c:initialize_tpm_device:417) Reading storage key(pub) using TPM service...
<3>2023-05-22T10:48:28Z [ERR!] (../src/hsm_client_tpm_device.c:hsm_client_tpm_sign_data:574) Invalid handle value specified handle: 0xaaaad7021160, data: 0xaaaad3b0d060, data_size: 128, digest: (nil), digest_size: 0xffffd7966128
{      ok} hsm_client_tpm_sign_data_key_NULL_fail
{ running} hsm_client_tpm_sign_data_keylen_NULL_fail
<6>2023-05-22T10:48:28Z [INFO] (../src/hsm_client_tpm_device.c:initialize_tpm_device:414) Reading endorsement key using TPM Service...
<6>2023-05-22T10:48:28Z [INFO] (../src/hsm_client_tpm_device.c:initialize_tpm_device:417) Reading storage key(pub) using TPM service...
<3>2023-05-22T10:48:28Z [ERR!] (../src/hsm_client_tpm_device.c:hsm_client_tpm_sign_data:574) Invalid handle value specified handle: 0xaaaad7021160, data: 0xaaaad3b0d060, data_size: 128, digest: 0xffffd7966128, digest_size: (nil)
{      ok} hsm_client_tpm_sign_data_keylen_NULL_fail
{ running} hsm_client_tpm_sign_data_succeed
<6>2023-05-22T10:48:28Z [INFO] (../src/hsm_client_tpm_device.c:initialize_tpm_device:414) Reading endorsement key using TPM Service...
<6>2023-05-22T10:48:28Z [INFO] (../src/hsm_client_tpm_device.c:initialize_tpm_device:417) Reading storage key(pub) using TPM service...
<6>2023-05-22T10:48:29Z [INFO] (../src/hsm_client_tpm_device.c:hsm_client_tpm_sign_data:581) HMAC-Signing the given message using TPM service...
{      ok} hsm_client_tpm_sign_data_succeed
{ running} hsm_client_tpm_interface_succeed
<6>2023-05-22T10:48:29Z [INFO] (../src/hsm_client_tpm_device.c:initialize_tpm_device:414) Reading endorsement key using TPM Service...
<6>2023-05-22T10:48:29Z [INFO] (../src/hsm_client_tpm_device.c:initialize_tpm_device:417) Reading storage key(pub) using TPM service...
{      ok} hsm_client_tpm_interface_succeed
{ summary} All tests succeeded!
```

**Review by eriknordmark — COMMENTED** [review]
When do we run the unit test? Is it manual or can be do it as part of a CI pipeline?

**Comment by shjala** [comment]
This repo has no CI configuration, so it is manual `cd azure-on-eve/tests && make test`.

**Pull request merged**
